### ISSUE TITLE
Some files are getting created

### ISSUE THREAD

**Issue by tarunkant** [KathanP19/JSFScan.sh#1]
Hello,

when I am running this tool, `jslinksecret.txt` and `endpoints.txt` are not getting created whereas other files are getting created such as `jsfile_links.txt`, `jsfiles`, `live_jsfile_links.txt`.

I ran this:

```
bash JSFScan.sh -l domains.txt -e -s -m -o pandao
```

where domains.txt contains:
```
https://pandao.ru
https://api.pandao.ru
https://www.pandao.ru
https://console.pandao.ru
```

**Comment by KathanP19** [comment]
can you check if interlace is installed properly?

**Comment by tarunkant** [comment]
Hello @KathanP19,

Yeah, Interlace is installed as stated in the description.
```py
python3 setup.py install
```

But it seems the interlace is not executing the command which has been put with `-c` flag.

**Comment by tarunkant** [comment]
Find your workspace to reset your password

You asked us to send you a password reset link for github.slack.com
[https://github.slack.com/?x=x-a1239917400512]. It turns out the email
address
reply@reply.​github.​com
doesn't have an account for that workspace yet.

If you’re pretty sure you do have an account, you can find your
workspace [https://slack.com/get-started] by trying a different email
address.

Please let us know [mailto:feedback@slack.com] if you have any other
questions or feedback.

Cheers,
The team at Slack

**Comment by KathanP19** [comment]
Try reinstalling it with sudo

**Comment by tarunkant** [comment]
Yeah, I did that too. I think this is the issue with interlace.

Thanks,

**Comment by KathanP19** [comment]
Let me know if you face any issue in using the script, closing this issue now. 
Thank you.
