### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by spazbg** [KathanP19/JSFScan.sh#10]
![image](https://user-images.githubusercontent.com/22222777/92073780-314db700-edbd-11ea-9c54-8bf1735d2716.png)

Any ideas on how to fix these errors. I am using JSFScan on Raspberry Pi 3

**Comment by KathanP19** [comment]
Check if you have cloned the latest version, and all the tools are installed properly.

**Comment by spazbg** [comment]
Yes, I just git clone the repo, and I think everything is installed normally. 
Additionally to the installation, I manually add chmod +x to all the .py files, and when I try to run all of the parts of the JSFScan, they are working.

**Comment by KathanP19** [comment]
can you check if live_jsfiles_link.txt file contains anything?

**Comment by KathanP19** [comment]
It seems its the same issue kindly check here #8

**Comment by spazbg** [comment]
Yep, I just apply the dirty fix from the Interlace repo, and the script now seems to work. 
Some files ain't downloaded but when I check their URLs they are missing for real. 
Only the js_var.txt is missing at the end with this error "mv: cannot stat 'js_var.txt': No such file or directory" now.
