### ISSUE TITLE
JSFScan.sh: line 21: gau: command not found JSFScan.sh: line 22: subjs: command not found

### ISSUE THREAD

**Issue by 0x0-0x0** [KathanP19/JSFScan.sh#13]
i found errors 

JSFScan.sh: line 21: gau: command not found
JSFScan.sh: line 22: subjs: command not found
JSFScan.sh: line 25: httpx: command not found
JSFScan.sh: line 37: interlace: command not found
JSFScan.sh: line 43: interlace: command not found
JSFScan.sh: line 50: interlace: command not found

mv: cannot stat 'endpoints.txt': No such file or directory
mv: cannot stat 'jslinksecret.txt': No such file or directory
mv: cannot stat 'jswordlist.txt': No such file or directory
mv: cannot stat 'js_var.txt': No such file or directory
mv: cannot stat 'domxss_scan.txt': No such file or directory

**Comment by bsysop** [comment]
😳 Have you read readme?

You need install...

```
$ sudo chmod +x install.sh
$ ./install.sh
```

**Comment by KathanP19** [comment]
Exactly, you can also try docker version

**Comment by ashhadali10** [comment]
i do all the step but it give error  line 22 subjs not found
