### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by bootyhunt3r** [KathanP19/JSFScan.sh#16]
Hey man , I tried to install with install.sh , and it did install but when I run the command , it throws some error and just show the .js files in the site , that's it. 
Can you recheck your script and update it if needed ?

**Comment by KathanP19** [comment]
can you share screenshot

**Comment by bootyhunt3r** [comment]
![Capture](https://user-images.githubusercontent.com/68128478/106551812-0d44fc00-653c-11eb-8712-46cb63c0a15e.PNG)

**Comment by bootyhunt3r** [comment]
I installed everthig , ran install.sh scripts a couple of times , but no luck

**Comment by bootyhunt3r** [comment]
![Capture](https://user-images.githubusercontent.com/68128478/106552386-42058300-653d-11eb-8bc6-77e79079b853.PNG)
![Capture2](https://user-images.githubusercontent.com/68128478/106552393-45007380-653d-11eb-9f13-00c35e1ef2c3.PNG)

**Comment by bootyhunt3r** [comment]
![Capture](https://user-images.githubusercontent.com/68128478/106554193-e4733580-6540-11eb-9830-ddb610def5e9.PNG)

Also tried docker version but it's also not workking, just getting struck at the starting

**Comment by KathanP19** [comment]
comment out `cat $target | hakrawler -js -cookie "cookie here" -depth 2 -scope subs -plain >> jsfile_links.txt` replace it with `#cat $target | hakrawler -js -cookie "cookie here" -depth 2 -scope subs -plain >> jsfile_links.txt` and httpx is not installed properly so go to httpx project discovery repo and install it , this should fix all the issue

**Comment by bootyhunt3r** [comment]
It's already commented out in the script.

**Comment by bootyhunt3r** [comment]
I think it's working now, I downloaded httpx manually and it's working now
