### ISSUE TITLE
Error while parsing target files if they have space in their path.

### ISSUE THREAD

**Issue by mostwanted002** [KathanP19/JSFScan.sh#17]
Since the target is being passed in bash script as `cat $target`, if files have space in their path, it creates an error, as it'll interpret the space as the separation between two file paths and will try to open both files.

Steps to reproduce:
1. Run `./JSFScan.sh -l /path/to/File\ that/has/space --all`.

Suggested fix:
Use `"<parameter>"` format in the script.
`cat "$target"` or `cat "${target}"` won't result in such problem.

**Comment by KathanP19** [comment]
Thank you for this issue and fix I push that in next update

**Comment by KathanP19** [comment]
@mostwanted002 Done Please check if its fixed
