### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by bootyhunt3r** [KathanP19/JSFScan.sh#18]
Hey man , 
Can you please look at the main script one more time, seems like there are a lot of errors , if you can just upgrade the script to like work correctly , cuz I have installed it in 3 different laptops and everytime it throws error , if you can just make it correct , this will be a dream tool. 
Thank you.

**Comment by KathanP19** [comment]
Try using docker version

**Comment by bootyhunt3r** [comment]
Sure , I'll try out that.

**Comment by the-maux** [comment]
Hello guyz, 
@bootyhunt3r try this run, but install latest go before 😉 :
``` bash
apt -y update && apt -y install git wget python3 python3-pip

# install python tools
git clone https://github.com/codingo/Interlace.git
git clone https://github.com/dark-warlord14/LinkFinder
git clone https://github.com/m4ll0k/SecretFinder.git

cat ./Interlace/requirements.txt > requirements.txt
cat ./SecretFinder/requirements.txt >> requirements.txt
cat ./LinkFinder/requirements.txt >> requirements.txt
pip3 install -r requirements.txt
cd Interlace && python3 ./setup.py install
cd LinkFinder && python3 ./setup.py install

# install go tools
go get github.com/tomnomnom/waybackurls
GO111MODULE=on go get -v github.com/lc/gau
GO111MODULE=on go get -v github.com/lc/subjs
GO111MODULE=on go get -v github.com/projectdiscovery/httpx/cmd/httpx
GO111MODULE=on go get -v github.com/hakluke/hakrawler
```

Maybe this can help

**Comment by bootyhunt3r** [comment]
Bro , the docker version is also not working , i tried using that , I just want the endpoints from the js files from the subdomains , do you have another alternative to just get the endpoints ?

**Comment by KathanP19** [comment]
Do this steps
1. Run install.sh as sudo
2. Send screenshots of error

**Comment by bootyhunt3r** [comment]
I did , I installed tools manually too , the process is running and taking a couple of mins to complete but then when I am opening that folder the endpoint file empty and some other files are also empty

**Comment by KathanP19** [comment]
screenshots please

**Comment by Davishankar** [comment]
Hey Kathan, I think I am getting a similar error as @bootyhunt3r. I will share my screenshots. So I installed it on an ubuntu vps. Followed the instructions for install.sh as mentioned on github. Now when writing the command this is what I am getting 
![image](https://user-images.githubusercontent.com/46703453/112531375-825ee000-8dcd-11eb-90d3-9a5f1a4b810f.png)
![image](https://user-images.githubusercontent.com/46703453/112531515-ac180700-8dcd-11eb-85a7-747f152dbe08.png)

**Comment by Davishankar** [comment]
Also, receiving the same error in Docker as well

**Comment by KathanP19** [comment]
@Davishankar its `--all` not `-all`

**Comment by Davishankar** [comment]
Hi @KathanP19  sorry that was a typing error. But i tried the command with the correct syntax as well, still not getting any output .

**Comment by KathanP19** [comment]
Can you share command you use and error you got, also share screenshot if possible.

**Comment by Davishankar** [comment]
The command and the error is attached below.
There is some problem when it is interacting with Interlace if I am not wrong.

![image](https://user-images.githubusercontent.com/46703453/113090947-898c5080-9208-11eb-9e50-52b20d40ccb8.png)

![image](https://user-images.githubusercontent.com/46703453/113090867-5b0e7580-9208-11eb-821b-062405cdce99.png)

**Comment by Davishankar** [comment]
@KathanP19

**Comment by KathanP19** [comment]
@Davishankar read the error it says no target or empty list that means the list you provided is empty or there is no available js file to scan. Closing this issue as it's not the error in the tool, create a new issue if there is a problem in the tool, Thank you.
