### ISSUE TITLE
Getting error while running ./JSFScan.sh

### ISSUE THREAD

**Issue by shripad5258** [KathanP19/JSFScan.sh#19]
Thanks...

![DeepinScreenshot_select-area_20210314230620](https://user-images.githubusercontent.com/65358061/111078086-ea820c00-8519-11eb-93af-ec950f9d0d7a.png)

**Comment by KathanP19** [comment]
can try simple `bash JSFScan.sh -l target.txt` and see if it produce the same error if yes then try the clean install again.

**Comment by KathanP19** [comment]
your welcome!
