### ISSUE TITLE
JSFScan.sh: line 22: subjs: command not found

### ISSUE THREAD

**Issue by ashhadali10** [KathanP19/JSFScan.sh#20]
ERROR 
JSFScan.sh: line 22: subjs: command not found
PLEASE SOLVE IT

**Comment by KathanP19** [comment]
Can you verify if subjs is installed on your system?

**Comment by ashhadali10** [comment]
yes is install subjs 
npm install -g subjs

**Comment by ashhadali10** [comment]
./install 
chmod +x  also but not working give error

**Comment by KathanP19** [comment]
npm ?  its `GO111MODULE=on go get -u -v github.com/lc/subjs`

**Comment by ashhadali10** [comment]
yes done  same error bro JSFScan.sh: line 22: subjs: command not found

**Comment by ashhadali10** [comment]
move   subjs in usr/local/bin 
solve my issue
