### ISSUE TITLE
cat: l: No such file or directory

### ISSUE THREAD

**Issue by ashhadali10** [KathanP19/JSFScan.sh#21]
now it give that error

[+] Started Gathering JsFiles-links

cat: l: No such file or directory
cat: l: No such file or directory

[+] Checking for live JsFiles-links

Usage: 
       -l   Gather Js Files Links
       -f   Import File Containing JS Urls
       -e   Gather Endpoints For JSFiles
       -s   Find Secrets For JSFiles
       -m   Fetch Js Files for manual testing
       -o   Make an Output Directory to put all things Together
       -w   Make a wordlist using words from jsfiles
       -v   Extract Vairables from the jsfiles
       -d   Scan for Possible DomXSS from jsfiles
mv: cannot stat 'endpoints.txt': No such file or directory
mv: cannot stat 'jslinksecret.txt': No such file or directory
mv: cannot stat 'jswordlist.txt': No such file or directory
mv: cannot stat 'js_var.txt': No such file or directory
mv: cannot stat 'domxss_scan.txt': No such file or directory
mv: cannot stat 'jsfiles/': No such file or directory

**Comment by KathanP19** [comment]
Send the command you used

**Comment by ashhadali10** [comment]
working know
