### ISSUE TITLE
cat: l: No such file or directory

### ISSUE THREAD

**Issue by bughuntersurya** [KathanP19/JSFScan.sh#22]
![js issue](https://user-images.githubusercontent.com/65324191/116347819-8df95880-a80a-11eb-8ec5-b13582b16553.png)

Command i Used
./JSFScan.sh -l target.txt -all -r -o target

target.txt contains https://target.com

**Comment by KathanP19** [comment]
its `--all`

**Comment by bughuntersurya** [comment]
hahhahaha sry it's not a issue of code it's issue of my eye.Thanks for the quick Response.
