### ISSUE TITLE
JSFScan.sh/./tools/jsbeautify.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by gprime31** [KathanP19/JSFScan.sh#32]
JSFScan.sh/./tools/jsbeautify.py': [Errno 2] No such file or directory

**Comment by gprime31** [comment]
![2021-12-06_11-25](https://user-images.githubusercontent.com/44535257/144883707-79827bc2-8cc4-41ba-8c1f-168a77ba4cd5.png)

**Comment by gprime31** [comment]
can't seem to find it.
want to check this tool out, looks interesting.

**Comment by gprime31** [comment]
grabbed it from https://github.com/gprime31/BBTz/blob/master/jsbeautify.py
looks like it's working ok now.

**Comment by KathanP19** [comment]
Closing this issue!!.
