### ISSUE TITLE
add 

### ISSUE THREAD

**Issue by Fawadkhanfk** [KathanP19/JSFScan.sh#4]
hy bro  add gwen githubsecret and github endpoint script

**Comment by Fawadkhanfk** [comment]
https://github.com/gwen001/github-search

**Comment by KathanP19** [comment]
bro that is for Github recon this script is mainly for javascript file recon, if you have a way to use it for js files let me know.

**Comment by KathanP19** [comment]
closing these issues, for now, thank you for suggesting. ;)
