### ISSUE TITLE
Produce error if not in home directory.

### ISSUE THREAD

**Issue by 0xabsiddique** [KathanP19/JSFScan.sh#5]
Mitigation:
change

./tools/..
to 
~/tools/..

thank you

**Comment by KathanP19** [comment]
It's not an issue, if you have ran the installation script then all the tools will get installed in the same dir as of `JSFScan.sh` script in ./tools/ dir. Try running `install.sh`  before running the main script.

Thank you for trying out, Hope you get lots of bugs. :)

**Comment by 0xabsiddique** [comment]
I believe you are not getting my point.Ya its works pretty well if you are in a directory like home/tools but if you try to run from home/recon/domains.txt it wont find other tools.i.e linkfinder.
Thank you.

**Comment by KathanP19** [comment]
can you share some screenshots and command you use to run.
