### ISSUE TITLE
Issue in Getjsbeautify filename

### ISSUE THREAD

**Issue by maverickNerd** [KathanP19/JSFScan.sh#7]
There is a problem with the awk is done for js files like these:

`https://x.cospace.app/m/services_v0.js\?v\=1.0.1`

Try this : filename=$(echo 'https://x.cospace.app/m/services_v0.js\?v\=1.0.1' | awk -F/ '{print $(NF-0)}');echo $filename

It will now output anything.

**Comment by KathanP19** [comment]
I don't see any difference can point out?

**Comment by maverickNerd** [comment]
nevermind, something messed up on my end.
